### ISSUE TITLE
Error when running requirement

### ISSUE THREAD

**Issue by Lin-Felix** [Mrguanglei/Instantmesh_scriptData#8]
Thx for the script！I‘new to this area，so questions below seem tricky for me

Here are my questions：
1. After running `conda create --name InsScri --file requirements.txt `，it says _The following packages are not available from current channels__

2. Should I run pip install requirement.txt？ but it also have problems，it says  _ERROR: Invalid requirement: 'libgcc_mutex==0.1==main' (from line 4 of requirements.txt)_

btw，dose README file have some errors，like conda creative --name Openlrm  python=3.9.19 -y , use create instead of creative

**Comment by Mrguanglei** [comment]
Thank you very much for pointing out, I have updated my code,
